addons:
  postgresql: "9.3"
  postgresql-9.3-postgis: "2.1"

services:
  - postgresql

language: python

python:
  - "2.7"

cache: pip

git:
  submodules: false

before_install:
  - pip install "setuptools>=18.5"
  - sleep 10

install:
  - pip install -r requirements.txt
  - cp config.json.sample config.json
  - export SIMPLIFIED_CONFIGURATION_FILE="$TRAVIS_BUILD_DIR/config.json"

before_script:
  - psql -c 'create user simplified_test;' -U postgres
  - psql -c 'create database simplified_library_registry_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres simplified_library_registry_test
  - psql -c 'create extension fuzzystrmatch;' -U postgres simplified_library_registry_test
  - psql -c 'grant all privileges on database simplified_library_registry_test to simplified_test;' -U postgres

script: ./test
