dist: focal

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12-postgis-3

services:
  - postgresql

language: python

python:
  - "3.9"

cache: pip

git:
  submodules: false

before_install:
  - pip install setuptools pipenv
  
install:
  - pipenv install

env:
  global:
    - SIMPLIFIED_TEST_DATABASE=postgres://simplified_test:simplified_test@localhost:5433/simplified_library_registry_test
    - PGPORT=5433
  
before_script:
  - psql -c 'CREATE USER simplified_test WITH PASSWORD '"'"'simplified_test'"'"';' -U travis -p 5433
  - psql -c 'CREATE DATABASE simplified_library_registry_test;' -U travis -p 5433
  - psql -c 'CREATE EXTENSION postgis;' -U travis simplified_library_registry_test -p 5433
  - psql -c 'CREATE EXTENSION fuzzystrmatch;' -U travis simplified_library_registry_test -p 5433
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE simplified_library_registry_test TO simplified_test;' -U travis -p 5433

script: pipenv run pytest -x tests
