dist: focal

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12-postgis-3

services:
  - postgresql

language: python

python:
  - "3.9"

cache: pip

git:
  submodules: false

before_install:
  - pip install setuptools pipenv
  
install:
  - pipenv install

env:
  - SIMPLIFIED_TEST_DATABASE="postgres://simplified_test:test@localhost:5433/simplified_library_registry_test"

before_script:
  - psql -c 'create user simplified_test;' -U postgres -p 5433
  - psql -c 'create database simplified_library_registry_test;' -U postgres -p 5433
  - psql -c 'create extension postgis;' -U postgres simplified_library_registry_test -p 5433
  - psql -c 'create extension fuzzystrmatch;' -U postgres simplified_library_registry_test -p 5433
  - psql -c 'grant all privileges on database simplified_library_registry_test to simplified_test;' -U postgres -p 5433

script: ./test
