addons:
  postgresql: "9.6"

services:
  - postgresql

language: python

python:
  - "2.7"

cache: pip

git:
  submodules: false

before_install:
  - pip install "setuptools>=18.5"
  - sudo apt-get install -y postgresql-9.6-postgis-2.4
  - sleep 10

install:
  - pip install -r requirements.txt

env:
  - SIMPLIFIED_TEST_DATABASE="postgres://simplified_test:test@localhost:5432/simplified_library_registry_test"

before_script:
  - psql -c 'create user simplified_test;' -U postgres
  - psql -c 'create database simplified_library_registry_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres simplified_library_registry_test
  - psql -c 'create extension fuzzystrmatch;' -U postgres simplified_library_registry_test
  - psql -c 'grant all privileges on database simplified_library_registry_test to simplified_test;' -U postgres

script: ./test
