version: "3.7"

services:
  registry_active_db:
    container_name: registry_active_db
    build:
      context: .
      target: libreg_local_db
    volumes:
      - registry_active_db:/var/lib/postgresql/data
    environment:
      - PGPORT=5433

<<<<<<< HEAD
  registry_active_webapp:
    container_name: registry_active_webapp
=======
  libreg_active_webapp:
    container_name: libreg_active_webapp
>>>>>>> origin/nypl-deploy-production
    depends_on: 
      - registry_active_db
    build:
      context: .
      target: libreg_active
      labels:
        - "com.nypl.docker.imagename=library_registry"
    environment:
      - SIMPLIFIED_TEST_DATABASE=postgresql://simplified_test:simplified_test@registry_active_db:5433/simplified_registry_test
      - SIMPLIFIED_PRODUCTION_DATABASE=postgresql://simplified:simplified@registry_active_db:5433/simplified_registry_dev
    ports:
      - "80:80"

volumes:
  registry_active_db:
