version: "3.7"

services:
  registry_db:
    container_name: registry_db
    build:
      context: .
      target: libreg_local_db
    volumes:
      - registry_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - PGPORT=5433

  registry_webapp:
    container_name: registry_webapp
    depends_on: 
      - registry_db
    build:
      context: .
      target: libreg_local
    ports:
      - "80:80"
    environment:
      - SIMPLIFIED_TEST_DATABASE=postgresql://simplified_test:simplified_test@registry_db:5433/simplified_registry_test
      - SIMPLIFIED_PRODUCTION_DATABASE=postgresql://simplified:simplified@registry_db:5433/simplified_registry_dev
    volumes:
      - type: bind
        source: .
        target: /simplye_app
        read_only: true

volumes:
  registry_db_data:
